version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/:/var/www/html
        ports:
            - 8001:8001
        restart: always
        depends_on:
            - php
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./src/:/var/www/html
    composer:
        image: composer
        volumes:
            - ./src/:/app
        command: install

